package com.example.charlie.finalproject.Characters;

import java.util.ArrayList;

public class Spell {
    public static final String[][] spells={
            //cantrip
            {"Acid Splash","save","dex","1d6",},//0
            {"Chill Touch" ,"attack","1d8",},
            {"Dancing Lights" ,},
            {"Druidcraft" ,},
            {"Eldritch Blast" ,"attack","1d10",},
            {"Fire Bolt" ,"attack","1d10",},
            {"Guidance" ,},
            {"Light" ,},
            {"Mage Hand" ,},
            {"Mending" ,},
            {"Message" ,},
            {"Minor Illusion" ,},
            {"Poison Spray" ,"save","con","1d12",},
            {"Prestidigitation" ,},
            {"Produce Flame" ,"attack","1d8",},
            {"Ray of Frost" ,"attack","1d8",},
            {"Resistance" ,},
            {"Sacred Flame" ,"save","dex","1d8",},
            {"Shillelagh","attack","1d8",},
            {"Shocking Grasp" ,"attack","1d8",},
            {"Spare the Dying" ,},
            {"Thaumaturgy",},
            {"True Strike" ,},
            {"Vicious Mockery","save","wis","1d4",},//23

            //1st level
            {"Alarm" ,},//24
            {"Animal Friendship" ,"save","wis",},
            {"Bane" ,"save","cha",},
            {"Bless" ,},
            {"Burning Hands" ,"save","dex","3d6",},
            {"Charm Person" ,"save","wis",},
            {"Color Spray" ,"6d10",},
            {"Command" ,"save","wis",},
            {"Comprehend Languages" ,},
            {"Create or Destroy Water" ,},
            {"Cure Wounds" ,"1d8+",},
            {"Detect Evil and Good" ,},
            {"Detect Magic" ,},
            {"Detect Poison and Disease" ,},
            {"Disguise Self" ,},
            {"Entangle" ,"save","str",},
            {"Expeditious Retreat" ,},
            {"Faerie Fire" ,"save","dex",},
            {"False Life" ,"1d4+4",},
            {"Feather Fall" ,},
            {"Find Familiar" ,},
            {"Floating Disk",},
            {"Fog Cloud" ,},
            {"Goodberry" ,},
            {"Grease" ,"save","dex",},
            {"Guiding Bolt" ,"attack","4d6",},
            {"Healing Word" ,"1d4+",},
            {"Hellish Rebuke" ,"save","dex","2d10",},
            {"Heroism" ,},
            {"Hideous Laughter" ,"save","wis",},
            {"Identify" ,},
            {"Illusory Script" ,},
            {"Inflict Wounds" ,"attack","3d10",},
            {"Jump" ,},
            {"Longstrider" ,},
            {"Mage Armor" ,},
            {"Magic Missile" ,"1d4+1",},
            {"Protection from Evil and Good" ,},
            {"Purify Food and Drink" ,},
            {"Sanctuary" ,},
            {"Shield" ,},
            {"Shield of Faith",},
            {"Silent Image" ,},
            {"Sleep" ,"5d8",},
            {"Speak with Animals" ,},
            {"Thunderwave" ,"save","con",},
            {"Unseen Servant",},
    };
}
